# Generated by Django 4.1.7 on 2023-04-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joke",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
