# Generated by Django 4.1.7 on 2023-04-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0006_alter_joke_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="joke",
            name="tags",
            field=models.ManyToManyField(blank=True, to="jokes.tag"),
        ),
    ]
